name: Build Common Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          4.8.x
          6.0.x
          9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build .NET Framework 4.8
      run: dotnet build --configuration Release --framework net48 --no-restore
    
    - name: Build .NET 6.0
      run: dotnet build --configuration Release --framework net6.0-windows --no-restore
    
    - name: Build .NET 9.0
      run: dotnet build --configuration Release --framework net9.0-windows --no-restore
    
    - name: Upload .NET Framework 4.8 build
      uses: actions/upload-artifact@v4
      with:
        name: Common-net48
        path: bin/Release/net48/
    
    - name: Upload .NET 6.0 build
      uses: actions/upload-artifact@v4
      with:
        name: Common-net6.0
        path: bin/Release/net6.0-windows/
    
    - name: Upload .NET 9.0 build
      uses: actions/upload-artifact@v4
      with:
        name: Common-net9.0
        path: bin/Release/net9.0-windows/
